employee_management_sys/employee_management_sys/materials/urls.py
from django.urls import path

from employee_management_sys.materials.views import MaterialAddView, MaterialListView, MaterialEditView, \
    MaterialDeleteView

urlpatterns = [
    path('add', MaterialAddView.as_view(), name='material add'),
    path('list', MaterialListView.as_view(), name='material list'),
    path('edit/<int:pk>', MaterialEditView.as_view(), name='material edit'),
    path('delete/<int:pk>', MaterialDeleteView.as_view(), name='material delete'),
]

employee_management_sys/employee_management_sys/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee_management_sys.base.urls')),
    path('cells/',include('employee_management_sys.cells.urls')),
    path('employees/',include('employee_management_sys.employees.urls')),
    path('orders/',include('employee_management_sys.orders.urls')),
    path('material/',include('employee_management_sys.materials.urls')),
]
handler404 = 'employee_management_sys.base.views.custom_page_not_found_view'
handler500 = 'employee_management_sys.base.views.custom_error_view'
handler403 = 'employee_management_sys.base.views.custom_permission_denied_view'
handler400 = 'employee_management_sys.base.views.custom_bad_request_view'

employee_management_sys/employee_management_sys/materials/models.py
from django.db import models

# Create your models here.

class Materials(models.Model):
    class Meta:
        ordering = ['name']
    name = models.CharField(
        max_length=255,
        unique=True,
    )
    quantity = models.PositiveIntegerField()

employee_management_sys/employee_management_sys/materials/forms.py
from django import forms

from employee_management_sys.materials.models import Materials


class MaterialForm(forms.ModelForm):
    class Meta:
        model = Materials
        fields = '__all__'

employee_management_sys/employee_management_sys/materials/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic as view

from employee_management_sys.materials.forms import MaterialForm
from employee_management_sys.materials.models import Materials


# Create your views here.

class MaterialAddView(view.CreateView):
    model = Materials
    login_url = reverse_lazy('login')
    redirect_field_name = reverse_lazy('material list')
    success_url = reverse_lazy('material list')
    template_name = 'materials/material-create.html'
    form_class = MaterialForm


class MaterialListView(view.ListView):
    login_url = reverse_lazy('login')
    redirect_field_name = reverse_lazy('material list')
    model = Materials
    template_name = 'materials/material-list.html'

class MaterialEditView(view.UpdateView):
    login_url = reverse_lazy('login')
    redirect_field_name = reverse_lazy('material list')
    model = Materials
    template_name = 'materials/material-edit.html'
    success_url = reverse_lazy('material list')
    form_class = MaterialForm


class MaterialDeleteView(view.DeleteView):
    login_url = reverse_lazy('login')
    redirect_field_name = reverse_lazy('material list')
    template_name = 'materials/material-delete.html'
    model = Materials
    fields = '__all__'
    success_url = reverse_lazy('material list')

employee_management_sys/templates/materials/material-create.html
{% extends 'base/base.html' %}
{% block title %}Material Creation{% endblock %}
{% block content %}

    <form method="post" action="{% url 'material add' %}">
        <div class="center-form-div">
            <div class="form-group">
                <div class="form-control form-text" style="font-size: 55px">
                    {{ form.as_p }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary " style="font-size: 60px;margin-left: 40%">Submit</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

employee_management_sys/templates/materials/material-delete.html
{% extends 'base/base.html' %}
{% block title %}Material Deletion{% endblock %}
{% block content %}
    <form method="post" action="{% url 'material delete'  pk=materials.pk %}">
        <div class="center-form-div">
            <div class="form-group">
                <div class="form-control form-text" style="font-size: 55px">
                    <h1 style="color: red;text-decoration: underline; text-align: center">Are you sure about deleting
                        material:
                    </h1>
                    <h1 style="text-align: center">Name : {{ materials.name }}</h1>
                    <h1 style="text-align: center">Quantity : {{ materials.quantity }}</h1>
                    {{ form.as_p }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary " style="font-size: 60px;margin-left: 40%">Delete
                    </button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

employee_management_sys/templates/materials/material-edit.html
{% extends 'base/base.html' %}
{% block title %} Material Edit{% endblock %}
{% block content %}
    <form method="post" action="{% url 'material edit' pk=materials.id %}">
        <div class="center-form-div">
            <div class="form-group">
                <div class="form-control form-text" style="font-size: 55px">
                    {{ form.as_p }}
                    {% csrf_token %}
                    <div>
                        <button type="submit" class="btn btn-primary " style="font-size: 60px;">Submit</button>
                        <button type="submit" class="btn btn-primary "
                                style="font-size: 60px;background-color: red;"><a style="text-decoration: none;color: white"
                                href="{% url 'material delete' pk=materials.pk %}">Delete</a></button>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

employee_management_sys/templates/materials/material-list.html
{% extends 'base/base.html' %}
{% load is_group %}
{% block title %}Material Listing{% endblock %}
{% block content %}

    {% if materials_list %}
        <div class="material-lister-ul">
            {% for material in materials_list %}
                <div class="material-list">
                    {% if request.user|is_group:'Editor' %}

                        <a href="{% url 'material edit' pk=material.id %}">
                            {{ material.name }}
                        </a>
                        <h1>Quantity: <b style="color: #2ec12e">{{ material.quantity }}</b></h1>
                    {% elif request.user.is_superuser %}
                        <a href="{% url 'material edit' pk=material.id %}">
                            {{ material.name }}
                        </a>
                        <h1>Quantity: <b style="color: #2ec12e">{{ material.quantity }}</b></h1>
                    {% else %}
                        <h1 style="font-size: 40px">{{ material.name }}</h1>
                        <h1>Quantity: <b style="color: #2ec12e">{{ material.quantity }}</b></h1>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h1 class="mat-not-found">No materials found</h1>
    {% endif %}
{% endblock %}