employee_management_sys/employee_management_sys/cells/urls.py
from django.urls import path

from employee_management_sys.cells.views import CellCreateView, CellDeleteView, CellDisplayView, CellManageView, \
    CellEditView

urlpatterns = [
    path('create', CellCreateView.as_view(), name='cell creation'),
    path('delete/<int:pk>', CellDeleteView.as_view(), name='cell deletion'),
    path('list', CellDisplayView.as_view(), name='cell list'),
    path('manage/<int:pk>', CellManageView.as_view(), name='cell manage'),
    path('edit/<int:pk>', CellEditView.as_view(), name='cell edit')

]

employee_management_sys/employee_management_sys/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee_management_sys.base.urls')),
    path('cells/',include('employee_management_sys.cells.urls')),
    path('employees/',include('employee_management_sys.employees.urls')),
    path('orders/',include('employee_management_sys.orders.urls')),
    path('material/',include('employee_management_sys.materials.urls')),
]
handler404 = 'employee_management_sys.base.views.custom_page_not_found_view'
handler500 = 'employee_management_sys.base.views.custom_error_view'
handler403 = 'employee_management_sys.base.views.custom_permission_denied_view'
handler400 = 'employee_management_sys.base.views.custom_bad_request_view'

employee_management_sys/employee_management_sys/cells/models.py
from django.db import models


# Create your models here.


class Cells(models.Model):
    class Meta:
        ordering = ['cell_name']

    cell_name = models.CharField(max_length=25, unique=True)

    def __repr__(self):
        return self.cell_name

    def __str__(self):
        return self.cell_name

employee_management_sys/employee_management_sys/cells/forms.py
from django import forms

from employee_management_sys.cells.models import Cells


class CellForm(forms.ModelForm):
    class Meta:
        model = Cells
        fields = '__all__'

employee_management_sys/employee_management_sys/cells/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic as views

from employee_management_sys.cells.forms import CellForm
# Create your views here.
from employee_management_sys.cells.models import Cells
from employee_management_sys.employees.models import Employee


class CellCreateView(LoginRequiredMixin, views.CreateView):
    form_class = CellForm
    login_url = reverse_lazy('login')
    redirect_field_name = reverse_lazy('cell list')
    template_name = 'cells/cell-create.html'
    model = Cells
    # fields = '__all__'
    success_url = reverse_lazy('cell list')


class CellDeleteView(LoginRequiredMixin, views.DeleteView):
    login_url = reverse_lazy('login')
    redirect_field_name = reverse_lazy('cell list')
    template_name = 'cells/cell-delete.html'
    model = Cells
    fields = '__all__'
    success_url = reverse_lazy('cell list')


class CellDisplayView(LoginRequiredMixin, views.ListView):
    login_url = reverse_lazy('login')
    redirect_field_name = reverse_lazy('cell list')
    model = Cells
    template_name = 'cells/cell-list.html'


class CellManageView(LoginRequiredMixin, views.DetailView):
    login_url = reverse_lazy('login')
    redirect_field_name = reverse_lazy('cell list')
    model = Cells
    template_name = 'cells/cells-manage.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['employee'] = Employee.objects.filter(cell=self.kwargs.get('pk'))
        return context


class CellEditView(LoginRequiredMixin, views.UpdateView):
    login_url = reverse_lazy('login')
    redirect_field_name = reverse_lazy('cell list')
    model = Cells
    template_name = 'cells/cells-edit.html'
    success_url = reverse_lazy('cell list')
    fields = '__all__'

employee_management_sys/templates/cells/cell-create.html
{% extends 'base/base.html' %}
{% block title %}Cell Creation{% endblock %}
{% block content %}
    <form method="post" action="{% url 'cell creation' %}">
        <div class="center-form-div">
            <div class="form-group">
                <div class="form-control form-text" style="font-size: 55px">
                    {{ form.as_p }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary " style="font-size: 60px;margin-left: 40%">Submit
                    </button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

employee_management_sys/templates/cells/cell-delete.html
{% extends 'base/base.html' %}
{% block title %}Cell Deletion{% endblock %}
{% block content %}
    <form method="post" action="{% url 'cell deletion'  pk=cells.pk%}">
        <div class="center-form-div">
            <div class="form-group">
                <div class="form-control form-text" style="font-size: 55px">
                    <h1 style="color: red;text-decoration: underline; text-align: center">Before deleting a cell first unassign all employees from it</h1>
                    <h1 style="text-align: center">Cell : {{ cells.cell_name }}</h1>
                    {{ form.as_p }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary " style="font-size: 60px;margin-left: 40%">Delete
                    </button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

employee_management_sys/templates/cells/cell-list.html
{% extends 'base/base.html' %}
{% block title %}Cell Listing{% endblock %}
{% block content %}
    {% if cells_list %}
{#        <div style="margin-left: 100px">#}
        <div class="cell-ul">
        {% for cell in cells_list %}
            <div class="cell-list">
                <a href="{% url 'cell manage' pk=cell.pk %}"
                   style="text-decoration: underline;font-size: 40px">
                    {{ cell.cell_name }} </a>
                </div>
        {% endfor %}
    {% else %}
        <h1 class="emp-not-found">No cells found</h1>
    {% endif %}
</div>
{% endblock %}

employee_management_sys/templates/cells/cells-edit.html
{% extends 'base/base.html' %}
{% block title %}Cell Edit{% endblock %}
{% block content %}
    <form method="post" action="{% url 'cell edit' pk=cells.id %}">
        <div class="center-form-div">
            <div class="form-group">
                <div class="form-control form-text" style="font-size: 55px">
                    {{ form.as_p }}
                    {% csrf_token %}
                    <div>
                        <button type="submit" class="btn btn-primary " style="font-size: 60px;">Submit</button>
                        <button type="submit" class="btn btn-primary "
                                style="font-size: 60px;background-color: red;"><a
                                style="text-decoration: none;color: white"
                                href="{% url 'cell deletion' pk=cells.pk %}">Delete</a></button>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

employee_management_sys/templates/cells/cells-manage.html
{% extends 'base/base.html' %}
{% load is_group %}
{% block title %}Cell Management{% endblock %}
{% block content %}
    <div style="text-align: center;color: #6dd317">
        <h1>{{ cells }}</h1>
        {% if user.is_superuser %}

            <a style="color: white" href="{% url 'cell edit' pk=cells.id %}">
                <button class="btn btn-primary " style="font-size: 40px;color: white;width: 150px;margin: 10px">Edit
                </button>
            </a>
        {% elif request.user.is_superuser %}
                        <a style="color: white" href="{% url 'cell edit' pk=cells.id %}">
                <button class="btn btn-primary " style="font-size: 40px;color: white;width: 150px;margin: 10px">Edit
                </button>
            </a>
        {% endif %}
    </div>
    {% if employee %}
        <div class="cell-ul">
            <ul>
                {% for emp in employee %}
                    <li>
                        <div class="cell-list">
                            {% if request.user|is_group:'Editor' %}
                                <a href="{% url 'employee edit' pk=emp.id %}">{{ emp.first_name }} {{ emp.last_name }}</a>
                                <h1 style="color: red"><b style="color: black">EMP ID:</b> {{ emp.emp_id }}</h1>
                            {% elif request.user.is_superuser %}
                                <a href="{% url 'employee edit' pk=emp.id %}">{{ emp.first_name }} {{ emp.last_name }}</a>
                                <h1 style="color: red"><b style="color: black">EMP ID:</b> {{ emp.emp_id }}</h1>
                            {% else %}
                                <h1>{{ emp.first_name }} {{ emp.last_name }}</h1>
                                <h1 style="color: red"><b style="color: black">EMP ID:</b> {{ emp.emp_id }}</h1>
                            {% endif %}
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% else %}
        <h1 class="cell-not-found">No employees in the cell</h1>
    {% endif %}
{% endblock %}