employee_management_sys/employee_management_sys/orders/urls.py
from django.urls import path

from employee_management_sys.orders.views import OrderAddView, OrderListView, OrderEditView, OrderDeleteView

urlpatterns = [
    path('add', OrderAddView.as_view(), name='order add'),
    path('list', OrderListView.as_view(), name='order list'),
    path('edit/<int:pk>', OrderEditView.as_view(), name='order edit'),
    path('delete/<int:pk>',OrderDeleteView.as_view(), name='order delete'),
]

employee_management_sys/employee_management_sys/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee_management_sys.base.urls')),
    path('cells/',include('employee_management_sys.cells.urls')),
    path('employees/',include('employee_management_sys.employees.urls')),
    path('orders/',include('employee_management_sys.orders.urls')),
    path('material/',include('employee_management_sys.materials.urls')),
]
handler404 = 'employee_management_sys.base.views.custom_page_not_found_view'
handler500 = 'employee_management_sys.base.views.custom_error_view'
handler403 = 'employee_management_sys.base.views.custom_permission_denied_view'
handler400 = 'employee_management_sys.base.views.custom_bad_request_view'

employee_management_sys/employee_management_sys/orders/models.py
from django.db import models
from django.core import validators

from employee_management_sys.cells.models import Cells

# Create your models here.

class Order(models.Model):
    class Meta:
        ordering = ['name']
    name = models.CharField(
        max_length=255,
        unique=True,
    )
    quantity = models.PositiveIntegerField()
    cell = models.OneToOneField(
        Cells,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )
    is_done = models.BooleanField()

    def __str__(self):
        return self.name

employee_management_sys/employee_management_sys/orders/forms.py
from django import forms

from employee_management_sys.orders.models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

employee_management_sys/employee_management_sys/orders/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic as view
from django.views.decorators.csrf import csrf_protect

from employee_management_sys.orders.forms import OrderForm
from employee_management_sys.orders.models import Order


# Create your views here.

class OrderAddView(view.CreateView):
    model = Order
    login_url = reverse_lazy('login')
    redirect_field_name = reverse_lazy('order list')
    success_url = reverse_lazy('order list')
    template_name = 'orders/order-create.html'
    form_class = OrderForm



class OrderListView(view.ListView):
    login_url = reverse_lazy('login')
    redirect_field_name = reverse_lazy('order list')
    model = Order
    template_name = 'orders/order-list.html'


class OrderEditView(view.UpdateView):
    login_url = reverse_lazy('login')
    redirect_field_name = reverse_lazy('order list')
    model = Order
    template_name = 'orders/order-edit.html'
    success_url = reverse_lazy('order list')
    form_class = OrderForm


class OrderDeleteView(view.DeleteView):
    login_url = reverse_lazy('login')
    redirect_field_name = reverse_lazy('order list')
    template_name = 'orders/order-delete.html'
    model = Order
    fields = '__all__'
    success_url = reverse_lazy('order list')

employee_management_sys/templates/orders/order-create.html
{% extends 'base/base.html' %}
{% block title %}Order Creation{% endblock %}
{% block content %}

    <form method="post" action="{% url 'order add' %}">
        <div class="center-form-div">
            <div class="form-group">
                <div class="form-control form-text" style="font-size: 55px" id="borders-as-p">
                    {{ form.as_p }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary " style="font-size: 60px;margin-left: 40%">Submit</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

employee_management_sys/templates/orders/order-delete.html
{% extends 'base/base.html' %}
{% block title %}Order Deletion{% endblock %}
{% block content %}
    <form method="post" action="{% url 'order delete'  pk=order.pk %}">
        <div class="center-form-div">
            <div class="form-group">
                <div class="form-control form-text" style="font-size: 55px">
                    <h1 style="color: red;text-decoration: underline; text-align: center">Are you sure about deleting
                        order:
                    </h1>
                    <h1 style="text-align: center">Name : {{ order.name }}</h1>
                    <h1 style="text-align: center">Quantity : {{ order.quantity }}</h1>
                    <h1 style="text-align: center">Cell : {{ order.cell }}</h1>
                    {{ form.as_p }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary " style="font-size: 60px;margin-left: 40%">Delete
                    </button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

employee_management_sys/templates/orders/order-edit.html
{% extends 'base/base.html' %}
{% block title %} Order Edit{% endblock %}
{% block content %}
    <form method="post" action="{% url 'order edit' pk=order.pk %}">
        <div class="center-form-div">
            <div class="form-group">
                <div class="form-control form-text" style="font-size: 55px">
                    {{ form.as_p }}
                    {% csrf_token %}
                    <div>
                        <button type="submit" class="btn btn-primary " style="font-size: 60px;">Submit</button>
                        <button type="submit" class="btn btn-primary "
                                style="font-size: 60px;background-color: red;"><a style="text-decoration: none;color: white"
                                href="{% url 'order delete' pk=order.pk %}">Delete</a></button>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

employee_management_sys/templates/orders/order-list.html
{% extends 'base/base.html' %}
{% load is_group %}
{% block title %}Order Listing{% endblock %}
{% block content %}

    {% if order_list %}
        <div class="order-lister-ul">
            {% for order in order_list %}
                <div class="order-list">
                    {% if request.user|is_group:'Editor' %}

                        <a href="{% url 'order edit' pk=order.pk %}">
                            {{ order.name }}</a>
                    {% elif request.user.is_superuser %}
                        <a href="{% url 'order edit' pk=order.pk %}">
                            {{ order.name }}</a>

                    {% else %}
                        <h1>{{ order.name }}</h1>
                    {% endif %}
                    {% if order.cell %}
                        <h1>Cell: <b style="color: #2ec12e">{{ order.cell }}</b></h1>

                    {% else %}
                        <h1>Cell: <b style="color: red">{{ order.cell }}</b></h1>
                    {% endif %}
                    {% if order.is_done %}
                        <h1>Done: <b style="color: #2ec12e">{{ order.is_done }}</b></h1>
                    {% else %}
                        <h1>Done: <b style="color: red">{{ order.is_done }}</b></h1>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h1 class="ord-not-found">No orders found</h1>
    {% endif %}
{% endblock %}