employee_management_sys/employee_management_sys/employees/urls.py
from django.urls import path

from employee_management_sys.employees.views import EmployeeCreateView, EmployeeListView, EmployeeEditView, \
    EmployeeDeleteView

urlpatterns = [
    path('create/', EmployeeCreateView.as_view(), name='employee creation'),
    path('list/', EmployeeListView.as_view(), name='employee list'),
    path('edit/<int:pk>', EmployeeEditView.as_view(), name='employee edit'),
    path('delete/<int:pk>', EmployeeDeleteView.as_view(), name='employee delete'),
]

employee_management_sys/employee_management_sys/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee_management_sys.base.urls')),
    path('cells/',include('employee_management_sys.cells.urls')),
    path('employees/',include('employee_management_sys.employees.urls')),
    path('orders/',include('employee_management_sys.orders.urls')),
    path('material/',include('employee_management_sys.materials.urls')),
]
handler404 = 'employee_management_sys.base.views.custom_page_not_found_view'
handler500 = 'employee_management_sys.base.views.custom_error_view'
handler403 = 'employee_management_sys.base.views.custom_permission_denied_view'
handler400 = 'employee_management_sys.base.views.custom_bad_request_view'

employee_management_sys/employee_management_sys/employees/models.py
from django.core import validators
from django.db import models

# Create your models here.
from employee_management_sys.base.validators import validate_only_letters
from employee_management_sys.cells.models import Cells


class Employee(models.Model):
    class Meta:
        ordering = ('first_name',)

    C01 = "C01"
    C02 = "C02"
    C03 = "C03"
    C04 = "C04"
    C05 = "C05"
    CELLS = (
        (C01, C01),
        (C02, C02),
        (C03, C03),
        (C04, C04),
        (C05, C05),
    )
    first_name = models.CharField(
        max_length=40,
        validators=(
            validate_only_letters,
            validators.MinLengthValidator(2),
        ),
        verbose_name='First Name',
        blank=False,
        null=False,
    )
    last_name = models.CharField(
        max_length=40,
        validators=(
            validate_only_letters,
            validators.MinLengthValidator(2),
        ),
        verbose_name='Last Name',
        blank=False,
        null=False,
    )

    cell = models.ManyToManyField(Cells)
    emp_id = models.CharField(
        max_length=7,
        unique=True,
        verbose_name='Employee Id'
    )

    def __repr__(self):
        return str(self.cell.get())

    def __str__(self):
        return f"{self.cell.get()}"

employee_management_sys/employee_management_sys/employees/forms.py
from django import forms

from employee_management_sys.employees.models import Employee


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'

    first_name = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    emp_id = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))

    def clean_email(self):
        return self.initial['first_name', 'last_name', 'emp_id']

employee_management_sys/employee_management_sys/employees/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic as views

# Create your views here.
from employee_management_sys.employees.forms import EmployeeForm
from employee_management_sys.employees.models import Employee


class EmployeeCreateView(LoginRequiredMixin, views.CreateView):
    login_url = reverse_lazy('login')
    redirect_field_name = reverse_lazy('employee list')
    template_name = 'employees/employee-create.html'
    model = Employee
    fields = '__all__'
    success_url = reverse_lazy('employee list')


class EmployeeListView(LoginRequiredMixin, views.ListView):
    login_url = reverse_lazy('login')
    redirect_field_name = reverse_lazy('employee list')
    model = Employee
    template_name = 'employees/employee-list.html'


class EmployeeEditView(LoginRequiredMixin, views.UpdateView):
    form_class = EmployeeForm
    login_url = reverse_lazy('login')
    redirect_field_name = reverse_lazy('employee list')
    model = Employee
    template_name = 'employees/employee-edit.html'
    success_url = reverse_lazy('employee list')


class EmployeeDeleteView(LoginRequiredMixin, views.DeleteView):
    login_url = reverse_lazy('login')
    redirect_field_name = reverse_lazy('employee list')
    model = Employee
    template_name = 'employees/employee-delete.html'
    success_url = reverse_lazy('employee list')

employee_management_sys/templates/employees/employee-create.html
{% extends 'base/base.html' %}
{% block title %}Employee Creation{% endblock %}
{% block content %}
    {#        <div class="form-bg">#}
    {#            <div class="create_form">#}
    {#                <form method="post" action="{% url 'employee creation' %}">#}
    {#                    {{ form.as_div }}#}
    {#                    {% csrf_token %}#}
    {#                    <button type="submit">Create</button>#}
    {#                </form>#}
    {#            </div>#}
    {#        </div>#}


    <form method="post" action="{% url 'employee creation' %}">
        <div class="center-form-div">
            <div class="form-group">
                <div class="form-control form-text" style="font-size: 55px">
                    {{ form.as_p }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary " style="font-size: 60px;margin-left: 40%">Submit</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

employee_management_sys/templates/employees/employee-delete.html
{% extends 'base/base.html' %}
{% block title %}Employee Deletion{% endblock %}
{% block content %}
    <div class="delete-profile">
        <h1>
            Are you sure you want to delete this employee?
        </h1>
        <div class="sure-buttons">
            <form method="post" action="{% url 'employee delete' pk=employee.pk%}">
                {% csrf_token %}
                <button class="btn btn-primary">Yes</button>
                <button class="btn btn-primary"><a href="javascript:history.back() " style="color: white">Go back</a></button>

            </form>
        </div>
    </div>
{% endblock %}

employee_management_sys/templates/employees/employee-edit.html
{% extends 'base/base.html' %}
{% block title %} Employee Edit{% endblock %}
{% block content %}
    <form method="post" action="{% url 'employee edit' pk=employee.pk %}">
        <div class="center-form-div">
            <div class="form-group">
                <div class="form-control form-text" style="font-size: 55px">
                    {{ form.as_p }}
                    {% csrf_token %}
                    <div>
                        <button type="submit" class="btn btn-primary " style="font-size: 60px;">Submit</button>
                        <button type="submit" class="btn btn-primary "
                                style="font-size: 60px;background-color: red;"><a style="text-decoration: none;color: white"
                                href="{% url 'employee delete' pk=employee.pk %}">Delete</a></button>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

employee_management_sys/templates/employees/employee-list.html
{% extends 'base/base.html' %}
{% load is_group %}
{% block title %}Employee Listing{% endblock %}
{% block content %}
    {% if employee_list %}
        <div class="employee-lister-ul">
            {% for employee in employee_list %}
                <div class="employee-list">
                    {% if request.user|is_group:'Editor' %}
                        <a href="{% url 'employee edit' pk=employee.pk %}">
                            {{ employee.first_name }} {{ employee.last_name }}</a>
                        <h1>{{ employee }}</h1>
                        <h1 style="color: red"><b style="color: black">EMP ID:</b> {{ employee.emp_id }}</h1>
                    {% elif request.user.is_superuser %}
                        <a href="{% url 'employee edit' pk=employee.pk %}">
                            {{ employee.first_name }} {{ employee.last_name }}</a>
                        <h1>{{ employee }}</h1>
                        <h1 style="color: red"><b style="color: black">EMP ID:</b> {{ employee.emp_id }}</h1>
                    {% else %}
                        <h1>{{ employee.first_name }} {{ employee.last_name }}</h1>
                        <h1>{{ employee }}</h1>
                        <h1 style="color: red"><b style="color: black">EMP ID:</b> {{ employee.emp_id }}</h1>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h1 class="emp-not-found">No employees found</h1>
    {% endif %}
{% endblock %}